# Generated by Django 4.2.2 on 2023-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("bot", "Bot")],
                default="user",
                max_length=20,
            ),
        ),
    ]
