# Generated by Django 4.2.2 on 2023-06-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0002_usermessage_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("system", "System")],
                default="user",
                max_length=20,
            ),
        ),
    ]
