# Generated by Django 4.2.2 on 2023-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0005_thread_chatmessage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="thread",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="thread",
            name="first_person",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="second_person",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
